name: Android APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Extract Project Files
      run: |
        unzip -o zara.zip
        # শুধু gradlew ফাইলটিকে রান করার পারমিশন দেওয়া হচ্ছে
        if [ -f "gradlew" ]; then
          chmod +x gradlew
        elif [ -f "zara/gradlew" ]; then
          mv zara/* .
          chmod +x gradlew
        fi

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: "**/build/outputs/apk/release/*.apk"
