name: Android APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Fresh Gradle Engine
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '9.3.1'
        cache-disabled: true

    - name: Extract Project Files from Workflow Folder
      run: |
        # যেহেতু ফাইলটি .github/workflows ফোল্ডারের ভেতরে আছে, তাই সেখান থেকে এটিকে এক্সট্র্যাক্ট করা হচ্ছে
        unzip -o .github/workflows/zara.zip
        rm -f gradle/wrapper/gradle-wrapper.jar
        gradle wrapper --gradle-version 9.3.1
        chmod +x gradlew

    - name: Force Clean Build Without Cache
      run: ./gradlew assembleRelease --no-daemon --no-configuration-cache --clean
      env:
        JAVA_HOME: ${{ env.JAVA_HOME }}

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: "**/build/outputs/apk/release/*.apk"
